<?php

/**
 * @file
 * Hook implementations for the audiofile module.
 */

/**
 * Implements hook_element_info().
 */
function audiofile_element_info() {
  $types['audiofile'] = [
    '#input' => TRUE,
    '#process' => ['audiofile_element_process'],
    '#element_validate' => ['audiofile_element_validate'],
    '#theme_wrappers' => ['form_element'],
    '#time_limit' => 300,
    '#upload_location' => NULL,
    '#upload_validators' => [
      'file_validate_extensions' => ['wav'],
    ],
    '#default_value' => NULL,
    '#theme_wrappers' => ['container'],
  ];
  return $types;
}

/**
 * Form-API process callback for audiofile elements.
 *
 * @see audiofile_element_info()
 */
function audiofile_element_process(array $element, array &$form_state, array $form) {
  $module_path = drupal_get_path('module', 'audiofile');
  $element['#attached']['js'][$module_path . '/audiofile.min.js'] = [
    'scope' => 'header',
    'group' => JS_LIBRARY,
    'preprocess' => FALSE,
  ];

  // Add a hidden fid field for storing the returned recorded file using ajax.
  $element['fid'] = array(
    '#type' => 'hidden',
    '#value' => $element['#default_value'],
  );

  return $element;
}

/**
 * Element validate callback for audiofile elements.
 *
 * @see audiofile_element_info()
 */
function audiofile_element_validate(array $element, array &$form_state, array $form) {
}
